from selenium.webdriver.common.by import By


class Locators:
    LOGIN_BUTTON = By.XPATH, "//button[text() = 'Вход и регистрация']"
    NO_ACCOUNT_BUTTON = By.XPATH, "//button[text() = 'Нет аккаунта']"
    INPUT_EMAIL = By.XPATH, "//input[@name='email']"
    INPUT_EMAIL_WRAPPER = By.XPATH, "//input[@name='email']/.."
    INPUT_PASSWORD = By.XPATH, "//input[@name = 'password']"
    INPUT_PASSWORD_WRAPPER = By.XPATH, "//input[@name = 'password']/.."
    INPUT_CONFIRM_PASSWORD = By.XPATH, "//input[@name = 'submitPassword']"
    INPUT_CONFIRM_PASSWORD_WRAPPER = By.XPATH, "//input[@name = 'submitPassword']/.."
    CREATE_ACCOUNT = By.XPATH, "//button[text() = 'Создать аккаунт']"
    AVATAR = By.XPATH, "//button[@class = 'circleSmall']"
    USER_NAME = By.XPATH, "//h3[@class = 'profileText name']"
    ERROR_MESSAGE = By.XPATH, "//span[text() = 'Ошибка']"
    SUBMIT_BUTTON = By.XPATH, "//button[text() = 'Войти']"
    LOGOUT_BUTTON = By.XPATH, "//button[text() = 'Выйти']"
    CREATE_ADVERTISEMENT = By.XPATH, "//button[text() = 'Разместить объявление']"
    ADD_ADVERTISEMENT = By.XPATH, "//button[text() = 'Разместить объявление']"
    MESSAGE_POPUP = By.XPATH, "//h1[text()= 'Чтобы разместить объявление, авторизуйтесь']"
    NAME_FIELD = By.XPATH, "//input[@placeholder = 'Название']"
    DESCRIPTION_FIELD = By.XPATH, "//textarea[@name='description']"
    PRICE_FIELD = By.XPATH, "//input[@name = 'price']"
    RADIO_BUTTON = By.XPATH, "//input[@value='Б/У']/.."
    CATEGORY = By.XPATH, "//input[@name='category']/../button"
    CHOOSE_CATEGORY = By.XPATH, "//span[text()= 'Книги']"
    CITY = By.XPATH, "//input[@name = 'city']/../button"
    CHOOSE_CITY = By.XPATH, "//span[text()= 'Новосибирск']"
    PUBLISH_BUTTON = By.XPATH, "//button[text() = 'Опубликовать']"
    APPLY_BUTTON = By.XPATH, "//button[text() = 'Применить']"
    MY_ADVERTISEMENTS = By.XPATH, "//div[@class='card']//h2[text()= 'Букварь']"
